  name: build-push
  on:
    push:
      branches:
        - 'automation'

  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: faturfawkes/mentutor_img:latest
        - 
          name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker stop mentutor
              docker rm mentutor
              docker rmi faturfawkes/mentutor_img
              docker run --name mentutor --link ${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_NAME=${{ secrets.DB_NAME }} -e ACCESS_KEY_IAM=${{ secrets.ACCESS_KEY_IAM }} -e SECRET_KEY_IAM=${{ secrets.SECRET_KEY_IAM }} -p 80:8080 -d faturfawkes/mentutor_img
