// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	forum "be12/mentutor/features/forum"

	mock "github.com/stretchr/testify/mock"
)

// DataInterface is an autogenerated mock type for the DataInterface type
type DataInterface struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *DataInterface) GetAll() ([]forum.Status, error) {
	ret := _m.Called()

	var r0 []forum.Status
	if rf, ok := ret.Get(0).(func() []forum.Status); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]forum.Status)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: data, token
func (_m *DataInterface) Insert(data forum.Status, token int) (int, error) {
	ret := _m.Called(data, token)

	var r0 int
	if rf, ok := ret.Get(0).(func(forum.Status, int) int); ok {
		r0 = rf(data, token)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(forum.Status, int) error); ok {
		r1 = rf(data, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertStatus provides a mock function with given fields: data, token
func (_m *DataInterface) InsertStatus(data forum.Status, token int) (forum.Status, error) {
	ret := _m.Called(data, token)

	var r0 forum.Status
	if rf, ok := ret.Get(0).(func(forum.Status, int) forum.Status); ok {
		r0 = rf(data, token)
	} else {
		r0 = ret.Get(0).(forum.Status)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(forum.Status, int) error); ok {
		r1 = rf(data, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDataInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewDataInterface creates a new instance of DataInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDataInterface(t mockConstructorTestingTNewDataInterface) *DataInterface {
	mock := &DataInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
