// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	admin "be12/mentutor/features/admin"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// UsecaseInterface is an autogenerated mock type for the UsecaseInterface type
type UsecaseInterface struct {
	mock.Mock
}

// AddNewClass provides a mock function with given fields: input, c
func (_m *UsecaseInterface) AddNewClass(input admin.ClassCore, c echo.Context) error {
	ret := _m.Called(input, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(admin.ClassCore, echo.Context) error); ok {
		r0 = rf(input, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUser provides a mock function with given fields: input, c
func (_m *UsecaseInterface) AddUser(input admin.UserCore, c echo.Context) (admin.UserCore, error) {
	ret := _m.Called(input, c)

	var r0 admin.UserCore
	if rf, ok := ret.Get(0).(func(admin.UserCore, echo.Context) admin.UserCore); ok {
		r0 = rf(input, c)
	} else {
		r0 = ret.Get(0).(admin.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(admin.UserCore, echo.Context) error); ok {
		r1 = rf(input, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteClass provides a mock function with given fields: id, c
func (_m *UsecaseInterface) DeleteClass(id uint, c echo.Context) error {
	ret := _m.Called(id, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, echo.Context) error); ok {
		r0 = rf(id, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: id, c
func (_m *UsecaseInterface) DeleteUser(id uint, c echo.Context) error {
	ret := _m.Called(id, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, echo.Context) error); ok {
		r0 = rf(id, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllClass provides a mock function with given fields: c
func (_m *UsecaseInterface) GetAllClass(c echo.Context) ([]admin.ClassCore, error) {
	ret := _m.Called(c)

	var r0 []admin.ClassCore
	if rf, ok := ret.Get(0).(func(echo.Context) []admin.ClassCore); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]admin.ClassCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUser provides a mock function with given fields: c
func (_m *UsecaseInterface) GetAllUser(c echo.Context) ([]admin.UserCore, []admin.UserCore, error) {
	ret := _m.Called(c)

	var r0 []admin.UserCore
	if rf, ok := ret.Get(0).(func(echo.Context) []admin.UserCore); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]admin.UserCore)
		}
	}

	var r1 []admin.UserCore
	if rf, ok := ret.Get(1).(func(echo.Context) []admin.UserCore); ok {
		r1 = rf(c)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]admin.UserCore)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(echo.Context) error); ok {
		r2 = rf(c)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSingleUser provides a mock function with given fields: id, c
func (_m *UsecaseInterface) GetSingleUser(id uint, c echo.Context) (admin.UserCore, error) {
	ret := _m.Called(id, c)

	var r0 admin.UserCore
	if rf, ok := ret.Get(0).(func(uint, echo.Context) admin.UserCore); ok {
		r0 = rf(id, c)
	} else {
		r0 = ret.Get(0).(admin.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, echo.Context) error); ok {
		r1 = rf(id, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClass provides a mock function with given fields: input, c
func (_m *UsecaseInterface) UpdateClass(input admin.ClassCore, c echo.Context) (admin.ClassCore, error) {
	ret := _m.Called(input, c)

	var r0 admin.ClassCore
	if rf, ok := ret.Get(0).(func(admin.ClassCore, echo.Context) admin.ClassCore); ok {
		r0 = rf(input, c)
	} else {
		r0 = ret.Get(0).(admin.ClassCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(admin.ClassCore, echo.Context) error); ok {
		r1 = rf(input, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserAdmin provides a mock function with given fields: input, c
func (_m *UsecaseInterface) UpdateUserAdmin(input admin.UserCore, c echo.Context) (admin.UserCore, error) {
	ret := _m.Called(input, c)

	var r0 admin.UserCore
	if rf, ok := ret.Get(0).(func(admin.UserCore, echo.Context) admin.UserCore); ok {
		r0 = rf(input, c)
	} else {
		r0 = ret.Get(0).(admin.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(admin.UserCore, echo.Context) error); ok {
		r1 = rf(input, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecaseInterface creates a new instance of UsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecaseInterface(t mockConstructorTestingTNewUsecaseInterface) *UsecaseInterface {
	mock := &UsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
