// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	mentor "be12/mentutor/features/mentor"

	mock "github.com/stretchr/testify/mock"
)

// RepoInterface is an autogenerated mock type for the RepoInterface type
type RepoInterface struct {
	mock.Mock
}

// EditProfileMentee provides a mock function with given fields: input
func (_m *RepoInterface) EditProfileMentee(input mentor.UserCore) (mentor.UserCore, error) {
	ret := _m.Called(input)

	var r0 mentor.UserCore
	if rf, ok := ret.Get(0).(func(mentor.UserCore) mentor.UserCore); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(mentor.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(mentor.UserCore) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditProfileMentor provides a mock function with given fields: input
func (_m *RepoInterface) EditProfileMentor(input mentor.UserCore) (mentor.UserCore, error) {
	ret := _m.Called(input)

	var r0 mentor.UserCore
	if rf, ok := ret.Get(0).(func(mentor.UserCore) mentor.UserCore); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(mentor.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(mentor.UserCore) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSingleMentee provides a mock function with given fields: id
func (_m *RepoInterface) GetSingleMentee(id uint) (mentor.UserCore, error) {
	ret := _m.Called(id)

	var r0 mentor.UserCore
	if rf, ok := ret.Get(0).(func(uint) mentor.UserCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(mentor.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSingleMentor provides a mock function with given fields: id
func (_m *RepoInterface) GetSingleMentor(id uint) (mentor.UserCore, error) {
	ret := _m.Called(id)

	var r0 mentor.UserCore
	if rf, ok := ret.Get(0).(func(uint) mentor.UserCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(mentor.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepoInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepoInterface creates a new instance of RepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepoInterface(t mockConstructorTestingTNewRepoInterface) *RepoInterface {
	mock := &RepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
