// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	mentor "be12/mentutor/features/mentor"

	mock "github.com/stretchr/testify/mock"
)

// UsecaseInterface is an autogenerated mock type for the UsecaseInterface type
type UsecaseInterface struct {
	mock.Mock
}

// UpdateProfile provides a mock function with given fields: input, id, role
func (_m *UsecaseInterface) UpdateProfile(input mentor.UserCore, id uint, role string) (mentor.UserCore, error) {
	ret := _m.Called(input, id, role)

	var r0 mentor.UserCore
	if rf, ok := ret.Get(0).(func(mentor.UserCore, uint, string) mentor.UserCore); ok {
		r0 = rf(input, id, role)
	} else {
		r0 = ret.Get(0).(mentor.UserCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(mentor.UserCore, uint, string) error); ok {
		r1 = rf(input, id, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecaseInterface creates a new instance of UsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecaseInterface(t mockConstructorTestingTNewUsecaseInterface) *UsecaseInterface {
	mock := &UsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
