  name: build-push
  on:
    push:
      branches:
        - 'main'

  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Load GCP Credentials
          shell: bash
          env:
            GCP: ${{ secrets.GCP }}
          run: |
            echo "$GCP" > keys.json
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}:latest
        - name: Connect to server using SSH
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              docker stop ${{ secrets.CONTAINER }}
              docker rm ${{ secrets.CONTAINER }}
              docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}
              docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}:latest
              docker run -d -p 80:8080 -e SERVER_PORT=${{ secrets.SERVERPORT }} -e GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} -e GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }} -e SECRET=${{ secrets.JWT_KEY }} -e DB_USERNAME=${{ secrets.DBUSER }} -e DB_PASSWORD=${{ secrets.DBPASS }} -e DB_HOST=${{ secrets.DBHOST }} -e DB_PORT=${{ secrets.DBPORT }} -e DB_NAME=${{ secrets.DBNAME }} --name ${{ secrets.CONTAINER }} ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}:latest
